[project]
name = 'Decentralized-Product-Lifecycle-Innovation-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.launch-optimization]
path = 'contracts/launch-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.testing-management]
path = 'contracts/testing-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
